### ISSUE TITLE
RequestError [HttpError]: Resource not accessible by integration

### ISSUE THREAD

**Issue by xobotyi** [cschleiden/jest-github-actions-reporter#9]
Weirdly, but tests for pull-request made by dependabot are failing.
Here is the run: https://github.com/react-hookz/web/pull/29/checks?check_run_id=2471766772#step:6:11

**Comment by cschleiden** [comment]
Looks like you are using a different action: 

```yaml
uses: mattallty/jest-github-action@v1.0.3
```

you should try to report it there 😃 

But the issue is that Dependabot PRs get a read-only token, which cannot be used to make PR comments: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by xobotyi** [comment]
Jeez🙈 sorry
